import type { Business, Review } from "@/types/business"

export const mockBusinesses: Business[] = [
  {
    id: "1",
    name: "Mindful Therapy Center",
    description:
      "Licensed therapists specializing in anxiety, depression, and trauma recovery. We offer individual, couples, and group therapy sessions with a holistic approach to mental wellness.",
    category: "Mental Health",
    subcategory: "Therapy & Counseling",
    location: {
      address: "123 Wellness Way",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    contact: {
      phone: "(415) 555-0123",
      email: "hello@mindfultherapy.com",
      website: "https://mindfultherapy.com",
    },
    tags: ["licensed", "insurance accepted", "virtual sessions", "individual therapy", "anxiety", "depression", "trauma", "LGBTQ+ friendly"],
    images: ["/cozy-coffee-shop.png"],
    hours: {
      monday: { open: "8:00", close: "20:00" },
      tuesday: { open: "8:00", close: "20:00" },
      wednesday: { open: "8:00", close: "20:00" },
      thursday: { open: "8:00", close: "20:00" },
      friday: { open: "8:00", close: "18:00" },
      saturday: { open: "9:00", close: "15:00" },
      sunday: { closed: true },
    },
    rating: 4.8,
    reviewCount: 127,
    verified: true,
    featured: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    name: "Nutrition Solutions by Dr. Sarah",
    description:
      "Registered Dietitian specializing in weight management, sports nutrition, and chronic disease prevention. Personalized meal planning and nutrition counseling.",
    category: "Nutrition & Dietetics",
    subcategory: "Clinical Nutrition",
    location: {
      address: "456 Health Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94103",
      coordinates: { lat: 37.7849, lng: -122.4094 },
    },
    contact: {
      phone: "(415) 555-0456",
      email: "info@nutritionsolutions.com",
      website: "https://nutritionsolutions.com",
    },
    tags: ["certified", "insurance accepted", "virtual sessions", "weight management", "sports nutrition", "meal planning", "evidence-based"],
    images: ["/computer-repair-shop.png"],
    hours: {
      monday: { open: "9:00", close: "18:00" },
      tuesday: { open: "9:00", close: "18:00" },
      wednesday: { open: "9:00", close: "18:00" },
      thursday: { open: "9:00", close: "18:00" },
      friday: { open: "9:00", close: "17:00" },
      saturday: { open: "10:00", close: "14:00" },
      sunday: { closed: true },
    },
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    featured: true,
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-18T11:15:00Z",
  },
  {
    id: "3",
    name: "FitLife Personal Training",
    description: "Certified personal trainers specializing in strength training, weight loss, and athletic performance. Customized workout plans and nutrition guidance.",
    category: "Fitness & Personal Training",
    subcategory: "Personal Training",
    location: {
      address: "789 Fitness Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94104",
      coordinates: { lat: 37.7649, lng: -122.4294 },
    },
    contact: {
      phone: "(415) 555-0789",
      email: "trainers@fitlifesf.com",
      website: "https://fitlifesf.com",
    },
    tags: ["certified", "personal training", "weight loss", "strength training", "yoga", "group training", "virtual sessions", "accessible"],
    images: ["/landscaped-garden.png"],
    hours: {
      monday: { open: "6:00", close: "21:00" },
      tuesday: { open: "6:00", close: "21:00" },
      wednesday: { open: "6:00", close: "21:00" },
      thursday: { open: "6:00", close: "21:00" },
      friday: { open: "6:00", close: "20:00" },
      saturday: { open: "7:00", close: "18:00" },
      sunday: { open: "8:00", close: "16:00" },
    },
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    featured: false,
    createdAt: "2024-01-05T08:00:00Z",
    updatedAt: "2024-01-22T16:45:00Z",
  },
  {
    id: "4",
    name: "Healing Hands Physical Therapy",
    description: "Licensed physical therapists providing rehabilitation services for sports injuries, chronic pain, and post-surgical recovery. Evidence-based treatment approaches.",
    category: "Physical Therapy",
    subcategory: "Sports Rehabilitation",
    location: {
      address: "321 Recovery Road",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
      coordinates: { lat: 37.7549, lng: -122.4094 },
    },
    contact: {
      phone: "(415) 555-0321",
      email: "appointments@healinghandspt.com",
      website: "https://healinghandspt.com",
    },
    tags: ["licensed", "insurance accepted", "sports rehabilitation", "chronic pain", "post-surgical", "evidence-based", "accessible", "bilingual"],
    images: ["/placeholder.jpg"],
    hours: {
      monday: { open: "7:00", close: "19:00" },
      tuesday: { open: "7:00", close: "19:00" },
      wednesday: { open: "7:00", close: "19:00" },
      thursday: { open: "7:00", close: "19:00" },
      friday: { open: "7:00", close: "18:00" },
      saturday: { open: "8:00", close: "14:00" },
      sunday: { closed: true },
    },
    rating: 4.9,
    reviewCount: 203,
    verified: true,
    featured: true,
    createdAt: "2024-01-12T07:00:00Z",
    updatedAt: "2024-01-25T10:30:00Z",
  },
  {
    id: "5",
    name: "Holistic Wellness Center",
    description: "Comprehensive wellness services including acupuncture, massage therapy, meditation classes, and nutritional counseling. Integrative approach to health and healing.",
    category: "Holistic Health",
    subcategory: "Integrative Medicine",
    location: {
      address: "654 Harmony Lane",
      city: "San Francisco",
      state: "CA",
      zipCode: "94106",
      coordinates: { lat: 37.7449, lng: -122.4294 },
    },
    contact: {
      phone: "(415) 555-0654",
      email: "wellness@holisticcenter.com",
      website: "https://holisticcenter.com",
    },
    tags: ["holistic", "acupuncture", "massage therapy", "meditation", "nutritional counseling", "sliding scale", "culturally sensitive", "virtual sessions"],
    images: ["/placeholder.jpg"],
    hours: {
      monday: { open: "9:00", close: "19:00" },
      tuesday: { open: "9:00", close: "19:00" },
      wednesday: { open: "9:00", close: "19:00" },
      thursday: { open: "9:00", close: "19:00" },
      friday: { open: "9:00", close: "18:00" },
      saturday: { open: "10:00", close: "16:00" },
      sunday: { open: "10:00", close: "15:00" },
    },
    rating: 4.6,
    reviewCount: 98,
    verified: true,
    featured: false,
    createdAt: "2024-01-08T09:30:00Z",
    updatedAt: "2024-01-23T14:20:00Z",
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    businessId: "1",
    userId: "user1",
    userName: "Sarah Johnson",
    rating: 5,
    comment: "Amazing coffee and great atmosphere! The baristas really know their craft.",
    createdAt: "2024-01-20T10:30:00Z",
    helpful: 12,
  },
  {
    id: "2",
    businessId: "1",
    userId: "user2",
    userName: "Mike Chen",
    rating: 4,
    comment: "Good coffee, but can get crowded during peak hours.",
    createdAt: "2024-01-18T14:15:00Z",
    helpful: 8,
  },
]

export const categories = [
  "Mental Health",
  "Nutrition & Dietetics",
  "Fitness & Personal Training",
  "Physical Therapy",
  "Alternative Medicine",
  "Wellness Coaching",
  "Medical Specialists",
  "Holistic Health",
  "Rehabilitation",
  "Preventive Care",
]

export const popularTags = [
  "licensed",
  "certified",
  "insurance accepted",
  "sliding scale",
  "virtual sessions",
  "in-person",
  "group therapy",
  "individual therapy",
  "family therapy",
  "couples counseling",
  "anxiety",
  "depression",
  "trauma",
  "addiction recovery",
  "weight management",
  "sports nutrition",
  "meal planning",
  "personal training",
  "yoga",
  "meditation",
  "acupuncture",
  "massage therapy",
  "chiropractic",
  "holistic",
  "evidence-based",
  "LGBTQ+ friendly",
  "culturally sensitive",
  "bilingual",
  "accessible",
  "emergency appointments",
]
