import type { Business, Review } from "@/types/business"

export const mockBusinesses: Business[] = [
  {
    id: "1",
    slug: "mindful-therapy-center",
    name: "Mindful Therapy Center",
    description:
      "Licensed therapists specializing in anxiety, depression, and trauma recovery. We offer individual, couples, and group therapy sessions with a holistic approach to mental wellness.",
    category: "Therapist",
    subcategory: "Mental Health Therapist",
    location: {
      address: "123 Wellness Way",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    contact: {
      phone: "(415) 555-0123",
      email: "hello@mindfultherapy.com",
      website: "https://mindfultherapy.com",
    },
    tags: ["licensed", "insurance accepted", "virtual sessions", "individual therapy", "anxiety", "depression", "trauma", "LGBTQ+ friendly"],
    images: ["/cozy-coffee-shop.png"],
    hours: {
      monday: { open: "8:00", close: "20:00" },
      tuesday: { open: "8:00", close: "20:00" },
      wednesday: { open: "8:00", close: "20:00" },
      thursday: { open: "8:00", close: "20:00" },
      friday: { open: "8:00", close: "18:00" },
      saturday: { open: "9:00", close: "15:00" },
      sunday: { open: "9:00", close: "15:00", closed: true },
    },
    rating: 4.8,
    reviewCount: 127,
    verified: true,
    featured: true,
    subscriptionStatus: "active",
    subscriptionPlan: "professional",
    services: [
      { name: "Individual Therapy", price: "$150/session", duration: "50 minutes" },
      { name: "Couples Counseling", price: "$180/session", duration: "60 minutes" },
      { name: "Group Therapy", price: "$75/session", duration: "90 minutes" },
    ],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    slug: "nutrition-solutions-sarah-chen",
    name: "Nutrition Solutions by Sarah Chen, RD",
    description:
      "Registered Dietitian specializing in weight management, sports nutrition, chronic disease prevention, and personalized meal planning.",
    category: "Registered Dietitian",
    subcategory: "Clinical Nutrition",
    location: {
      address: "456 Health Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94103",
      coordinates: { lat: 37.7849, lng: -122.4094 },
    },
    contact: {
      phone: "(415) 555-0456",
      email: "sarah@nutritionsolutions.com",
      website: "https://nutritionsolutions.com",
    },
    tags: ["registered dietitian", "insurance accepted", "virtual sessions", "weight management", "sports nutrition", "meal planning", "diabetes management", "evidence-based"],
    images: ["/computer-repair-shop.png"],
    hours: {
      monday: { open: "9:00", close: "18:00" },
      tuesday: { open: "9:00", close: "18:00" },
      wednesday: { open: "9:00", close: "18:00" },
      thursday: { open: "9:00", close: "18:00" },
      friday: { open: "9:00", close: "17:00" },
      saturday: { open: "10:00", close: "14:00" },
      sunday: { open: "10:00", close: "14:00", closed: true },
    },
    rating: 4.8,
    reviewCount: 98,
    verified: true,
    featured: false,
    subscriptionStatus: "active",
    subscriptionPlan: "professional",
    services: [
      { name: "Nutrition Consultation", price: "$130/session", duration: "60 minutes" },
      { name: "Meal Planning Service", price: "$200/month", duration: "Ongoing" },
      { name: "Follow-up Session", price: "$80/session", duration: "30 minutes" },
    ],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-18T11:15:00Z",
  },
  {
    id: "3",
    slug: "dr-michael-johnson-psychiatry",
    name: "Dr. Michael Johnson Psychiatry",
    description: "Board-certified psychiatrist specializing in mood disorders, anxiety, ADHD, and medication management. Comprehensive psychiatric evaluations and ongoing care.",
    category: "Psychiatrist",
    subcategory: "Adult Psychiatry",
    location: {
      address: "789 Fitness Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94104",
      coordinates: { lat: 37.7649, lng: -122.4294 },
    },
    contact: {
      phone: "(415) 555-0789",
      email: "contact@drjohnsonpsych.com",
      website: "https://drjohnsonpsych.com",
    },
    tags: ["board certified", "insurance accepted", "virtual sessions", "medication management", "anxiety", "depression", "ADHD", "evidence-based"],
    images: ["/landscaped-garden.png"],
    hours: {
      monday: { open: "9:00", close: "18:00" },
      tuesday: { open: "9:00", close: "18:00" },
      wednesday: { open: "9:00", close: "18:00" },
      thursday: { open: "9:00", close: "18:00" },
      friday: { open: "9:00", close: "17:00" },
      saturday: { open: "10:00", close: "14:00" },
      sunday: { closed: true },
    },
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    featured: true,
    subscriptionStatus: "active",
    subscriptionPlan: "premium",
    services: [
      { name: "Psychiatric Evaluation", price: "$300/session", duration: "90 minutes" },
      { name: "Medication Management", price: "$150/session", duration: "30 minutes" },
      { name: "Psychotherapy Session", price: "$200/session", duration: "50 minutes" },
    ],
    createdAt: "2024-01-05T08:00:00Z",
    updatedAt: "2024-01-22T16:45:00Z",
  },
  {
    id: "4",
    slug: "wellness-life-coaching",
    name: "Wellness Life Coaching",
    description: "Certified health coaches helping you achieve your wellness goals through personalized guidance, accountability, and lifestyle optimization strategies.",
    category: "Health Coach",
    subcategory: "Wellness Coach",
    location: {
      address: "321 Recovery Road",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
      coordinates: { lat: 37.7549, lng: -122.4094 },
    },
    contact: {
      phone: "(415) 555-0321",
      email: "hello@wellnesslifecoaching.com",
      website: "https://wellnesslifecoaching.com",
    },
    tags: ["certified", "holistic approach", "virtual sessions", "stress management", "lifestyle optimization", "goal setting", "accountability", "work-life balance"],
    images: ["/placeholder.jpg"],
    hours: {
      monday: { open: "7:00", close: "20:00" },
      tuesday: { open: "7:00", close: "20:00" },
      wednesday: { open: "7:00", close: "20:00" },
      thursday: { open: "7:00", close: "20:00" },
      friday: { open: "7:00", close: "19:00" },
      saturday: { open: "8:00", close: "15:00" },
      sunday: { open: "9:00", close: "14:00" },
    },
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    featured: true,
    subscriptionStatus: "active",
    subscriptionPlan: "basic",
    services: [
      { name: "Initial Consultation", price: "$120/session", duration: "60 minutes" },
      { name: "Ongoing Coaching", price: "$90/session", duration: "45 minutes" },
      { name: "Group Coaching", price: "$40/session", duration: "60 minutes" },
    ],
    createdAt: "2024-01-12T07:00:00Z",
    updatedAt: "2024-01-25T10:30:00Z",
  },
  {
    id: "5",
    slug: "elite-personal-training-studio",
    name: "Elite Personal Training Studio",
    description: "Certified personal trainers specializing in strength training, weight loss, and athletic performance. One-on-one training and small group sessions available.",
    category: "Personal Trainer",
    subcategory: "Strength & Conditioning",
    location: {
      address: "654 Harmony Lane",
      city: "San Francisco",
      state: "CA",
      zipCode: "94106",
      coordinates: { lat: 37.7449, lng: -122.4294 },
    },
    contact: {
      phone: "(415) 555-0654",
      email: "info@eliteptstudio.com",
      website: "https://eliteptstudio.com",
    },
    tags: ["certified", "NASM certified", "strength training", "weight loss", "athletic performance", "nutrition guidance", "flexible scheduling"],
    images: ["/placeholder.jpg"],
    hours: {
      monday: { open: "6:00", close: "21:00" },
      tuesday: { open: "6:00", close: "21:00" },
      wednesday: { open: "6:00", close: "21:00" },
      thursday: { open: "6:00", close: "21:00" },
      friday: { open: "6:00", close: "20:00" },
      saturday: { open: "7:00", close: "18:00" },
      sunday: { open: "8:00", close: "15:00" },
    },
    rating: 4.9,
    reviewCount: 203,
    verified: true,
    featured: true,
    subscriptionStatus: "active",
    subscriptionPlan: "professional",
    services: [
      { name: "Personal Training Session", price: "$85/session", duration: "60 minutes" },
      { name: "Small Group Training", price: "$35/session", duration: "60 minutes" },
      { name: "Fitness Assessment", price: "$50/assessment", duration: "45 minutes" },
    ],
    createdAt: "2024-01-08T09:30:00Z",
    updatedAt: "2024-01-23T14:20:00Z",
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    businessId: "1",
    userId: "user1",
    userName: "Sarah Johnson",
    rating: 5,
    comment: "Dr. Smith helped me work through my anxiety with such compassion and expertise. The virtual sessions were just as effective as in-person.",
    createdAt: "2024-01-20T10:30:00Z",
    helpful: 12,
  },
  {
    id: "2",
    businessId: "1",
    userId: "user2",
    userName: "Mike Chen",
    rating: 4,
    comment: "Great therapist! Really helped me understand my depression and provided practical coping strategies.",
    createdAt: "2024-01-18T14:15:00Z",
    helpful: 8,
  },
]

export const categories = [
  "Therapist",
  "Psychiatrist",
  "Health Coach",
  "Personal Trainer",
  "Registered Dietitian",
]

export const popularTags = [
  "licensed",
  "certified",
  "insurance accepted",
  "sliding scale",
  "virtual sessions",
  "in-person",
  "group therapy",
  "individual therapy",
  "family therapy",
  "couples counseling",
  "anxiety",
  "depression",
  "trauma",
  "addiction recovery",
  "chronic pain",
  "sports injuries",
  "post-surgical",
  "rehabilitation",
  "physical therapy",
  "occupational therapy",
  "speech therapy",
  "chiropractic",
  "pain management",
  "evidence-based",
  "LGBTQ+ friendly",
  "culturally sensitive",
  "bilingual",
  "accessible",
  "emergency appointments",
  "pediatric care",
  "geriatric care",
  "mental health",
  "behavioral health",
]
